# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
