# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-07 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=60)),
                ('album', models.CharField(blank=True, max_length=120)),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
